[package]
name = "ch03-request-response"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }
serde = {version = "1.0.116", features = ["derive"]}
tide = "0.15.0"
